#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DkVideoPlayer.Resource", IsApplication=false)]

namespace DkVideoPlayer
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int enableAudioFocus = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int looping = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int playerBackgroundColor = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int screenScaleType = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public static int dkplayer_background_color = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int dkplayer_theme_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int dkplayer_theme_color_translucent = 2130837506;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public static int dkplayer_controller_height = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int dkplayer_controller_icon_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int dkplayer_controller_seekbar_max_size = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int dkplayer_controller_seekbar_size_n = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int dkplayer_controller_seekbar_size_s = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int dkplayer_controller_text_size = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int dkplayer_controller_time_text_size = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int dkplayer_default_spacing = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int dkplayer_play_btn_size = 2130903048;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public static int dkplayer_battery_level = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int dkplayer_ic_action_arrow_back = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int dkplayer_ic_action_autorenew = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int dkplayer_ic_action_battery = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int dkplayer_ic_action_battery_10 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int dkplayer_ic_action_battery_20 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public static int dkplayer_ic_action_battery_30 = 2130968582;
			
			// aapt resource value: 0x7F040007
			public static int dkplayer_ic_action_battery_40 = 2130968583;
			
			// aapt resource value: 0x7F040008
			public static int dkplayer_ic_action_battery_50 = 2130968584;
			
			// aapt resource value: 0x7F040009
			public static int dkplayer_ic_action_battery_60 = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public static int dkplayer_ic_action_battery_70 = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public static int dkplayer_ic_action_battery_80 = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public static int dkplayer_ic_action_battery_90 = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public static int dkplayer_ic_action_brightness = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public static int dkplayer_ic_action_close = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public static int dkplayer_ic_action_fast_forward = 2130968591;
			
			// aapt resource value: 0x7F040010
			public static int dkplayer_ic_action_fast_rewind = 2130968592;
			
			// aapt resource value: 0x7F040011
			public static int dkplayer_ic_action_fullscreen = 2130968593;
			
			// aapt resource value: 0x7F040012
			public static int dkplayer_ic_action_fullscreen_exit = 2130968594;
			
			// aapt resource value: 0x7F040013
			public static int dkplayer_ic_action_lock_close = 2130968595;
			
			// aapt resource value: 0x7F040014
			public static int dkplayer_ic_action_lock_open = 2130968596;
			
			// aapt resource value: 0x7F040015
			public static int dkplayer_ic_action_pause = 2130968597;
			
			// aapt resource value: 0x7F040016
			public static int dkplayer_ic_action_play_arrow = 2130968598;
			
			// aapt resource value: 0x7F040017
			public static int dkplayer_ic_action_replay = 2130968599;
			
			// aapt resource value: 0x7F040018
			public static int dkplayer_ic_action_volume_off = 2130968600;
			
			// aapt resource value: 0x7F040019
			public static int dkplayer_ic_action_volume_up = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public static int dkplayer_layer_progress_bar = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public static int dkplayer_progress_loading = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public static int dkplayer_seekbar_thumb = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public static int dkplayer_seekbar_thumb_normal = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public static int dkplayer_seekbar_thumb_pressed = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public static int dkplayer_selector_full_screen_button = 2130968607;
			
			// aapt resource value: 0x7F040020
			public static int dkplayer_selector_lock_button = 2130968608;
			
			// aapt resource value: 0x7F040021
			public static int dkplayer_selector_play_button = 2130968609;
			
			// aapt resource value: 0x7F040022
			public static int dkplayer_shape_back_bg = 2130968610;
			
			// aapt resource value: 0x7F040023
			public static int dkplayer_shape_play_bg = 2130968611;
			
			// aapt resource value: 0x7F040024
			public static int dkplayer_shape_standard_controller_top_bg = 2130968612;
			
			// aapt resource value: 0x7F040025
			public static int dkplayer_shape_stardard_controller_bottom_bg = 2130968613;
			
			// aapt resource value: 0x7F040026
			public static int dkplayer_shape_status_view_btn = 2130968614;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public static int bottom_container = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int bottom_progress = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int center_container = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int complete_container = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int curr_time = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int iv_battery = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int iv_icon = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int iv_play = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int iv_refresh = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int iv_replay = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int loading = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int @lock = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int message = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int net_warning_layout = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int pro_percent = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int seekBar = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int start_play = 2131034128;
			
			// aapt resource value: 0x7F050011
			public static int status_btn = 2131034129;
			
			// aapt resource value: 0x7F050012
			public static int stop_fullscreen = 2131034130;
			
			// aapt resource value: 0x7F050013
			public static int sys_time = 2131034131;
			
			// aapt resource value: 0x7F050014
			public static int thumb = 2131034132;
			
			// aapt resource value: 0x7F050015
			public static int title = 2131034133;
			
			// aapt resource value: 0x7F050016
			public static int title_container = 2131034134;
			
			// aapt resource value: 0x7F050017
			public static int total_time = 2131034135;
			
			// aapt resource value: 0x7F050018
			public static int tv_percent = 2131034136;
			
			// aapt resource value: 0x7F050019
			public static int type_16_9 = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public static int type_4_3 = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public static int type_center_crop = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public static int type_default = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public static int type_match_parent = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public static int type_original = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public static int dkplayer_layout_complete_view = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int dkplayer_layout_error_view = 2131099649;
			
			// aapt resource value: 0x7F060002
			public static int dkplayer_layout_gesture_control_view = 2131099650;
			
			// aapt resource value: 0x7F060003
			public static int dkplayer_layout_live_control_view = 2131099651;
			
			// aapt resource value: 0x7F060004
			public static int dkplayer_layout_prepare_view = 2131099652;
			
			// aapt resource value: 0x7F060005
			public static int dkplayer_layout_standard_controller = 2131099653;
			
			// aapt resource value: 0x7F060006
			public static int dkplayer_layout_title_view = 2131099654;
			
			// aapt resource value: 0x7F060007
			public static int dkplayer_layout_vod_control_view = 2131099655;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public static int dkplayer_continue_play = 2131165184;
			
			// aapt resource value: 0x7F070001
			public static int dkplayer_error_message = 2131165185;
			
			// aapt resource value: 0x7F070003
			public static int dkplayer_locked = 2131165187;
			
			// aapt resource value: 0x7F070002
			public static int dkplayer_lock_tip = 2131165186;
			
			// aapt resource value: 0x7F070004
			public static int dkplayer_replay = 2131165188;
			
			// aapt resource value: 0x7F070005
			public static int dkplayer_retry = 2131165189;
			
			// aapt resource value: 0x7F070006
			public static int dkplayer_unlocked = 2131165190;
			
			// aapt resource value: 0x7F070007
			public static int dkplayer_wifi_tip = 2131165191;
			
			// aapt resource value: 0x7F070008
			public static int ijkplayer_dummy = 2131165192;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003 }
			public static int[] VideoView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public static int VideoView_enableAudioFocus = 0;
			
			// aapt resource value: 1
			public static int VideoView_looping = 1;
			
			// aapt resource value: 2
			public static int VideoView_playerBackgroundColor = 2;
			
			// aapt resource value: 3
			public static int VideoView_screenScaleType = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
